baseurl = "http://cesarvr.github.io/"
title = "César"
author = "Cesar Valdez"
canonifyurls = true
languagecode = "en"
theme = "vec"
paginate = 15

#pygmentsstyle       = "bw"
#pygmentscodefences  = true

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = "UA-21473132-2"


[params]
  sitename = "César"
  Keywords = "key, 关键字, キーワード"
  Description = "There are some words to describe your site"

  Avater = "img/avatar.jpg"
  SelfIntro = "Mobile & Node.js Developer"


[[menu.main]]
    name = "Posts"
    url  = "/post"
[[menu.main]]
    name = "Projects"
    url  = "https://github.com/cesarvr"
[[menu.main]]
    name = "Resume"
    url  = "https://ie.linkedin.com/in/cesarvr"
