baseurl = "http://cesarvr.github.io/"
title = "Brain Drops"
author = "Cesar Valdez"
canonifyurls = true
languagecode = "en"
theme = "black-and-light"

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "César"

[[menu.main]]
    name = "About"
    url  = "https://github.com/davidhampgonsalves/hugo-black-and-light-theme"
[[menu.main]]
    name = "Projects"
    url  = "https://github.com/cesarvr"
[[menu.main]]
    name = "Resume"
    url  = "https://ie.linkedin.com/in/cesarvr"
